export { architectureChecks } from './architecture.js';
export { dependencyChecks } from './dependencies.js';
export { typescriptChecks } from './typescript.js';
export { testChecks } from './test.js';
export { securityChecks } from './security.js';
export { performanceChecks } from './performance.js';
export { envChecks } from './env.js';
export { maintainabilityChecks } from './maintainability.js';
export { duplicateChecks } from './duplicates.js';