import type { ScanResult } from '@software-mri/core';

export function generateMarkdownReport(result: ScanResult): string {
  const lines: string[] = [];

  lines.push(`# Software MRI Report: ${result.project.name}`);
  lines.push('');
  lines.push(`> Generated for **${result.project.name}**`);
  lines.push(`> Frameworks: ${result.project.frameworks.join(', ') || 'None detected'}`);
  lines.push(`> Package Manager: ${result.project.packageManager}`);
  lines.push(`> Files scanned: ${result.scannedFiles}`);
  lines.push(`> Duration: ${formatDuration(result.scanDurationMs)}`);
  lines.push('');

  lines.push('## Production Readiness Score');
  lines.push('');
  lines.push(`**${result.totalScore}%**`);
  lines.push('');
  lines.push(generateScoreBar(result.totalScore));
  lines.push('');

  lines.push('## Category Scores');
  lines.push('');
  lines.push('| Category | Score | Status | Issues |');
  lines.push('|----------|-------|--------|--------|');
  for (const cat of result.categories) {
    const statusIcon = cat.status === 'pass' ? '✅' : cat.status === 'warn' ? '⚠️' : '❌';
    lines.push(`| ${getCategoryLabel(cat.category)} | ${cat.score}% | ${statusIcon} ${cat.status} | ${cat.issues.length} |`);
  }
  lines.push('');

  lines.push('## Issues');
  lines.push('');
  for (const cat of result.categories) {
    if (cat.issues.length === 0) continue;
    lines.push(`### ${getCategoryLabel(cat.category)}`);
    lines.push('');

    for (const issue of cat.issues) {
      const severityBadge = getSeverityBadge(issue.severity);
      const confidenceBadge = `*confidence: ${issue.confidence}*`;
      lines.push(`#### ${severityBadge} ${issue.title} ${confidenceBadge}`);
      lines.push('');
      lines.push(`**ID:** \`${issue.id}\``);
      lines.push('');
      lines.push(issue.description);
      lines.push('');

      if (issue.files.length > 0) {
        lines.push('**Affected files:**');
        for (const file of issue.files) {
          lines.push(`- \`${file}\``);
        }
        lines.push('');
      }

      lines.push('**Tips:**');
      for (const tip of issue.tips) {
        lines.push(`- ${tip}`);
      }
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('');
  lines.push('*Report generated by Software MRI v0.1.1*');

  return lines.join('\n');
}

function getCategoryLabel(id: string): string {
  const labels: Record<string, string> = {
    architecture: 'Architecture',
    dependencies: 'Dependencies',
    deadCode: 'Dead Code',
    duplicates: 'Duplicates',
    typeSafety: 'Type Safety',
    testCoverage: 'Test Coverage',
    configHealth: 'Config Health',
    securityHygiene: 'Security',
    performanceRisk: 'Performance',
    maintainability: 'Maintainability',
  };
  return labels[id] || id;
}

function getSeverityBadge(severity: string): string {
  const badges: Record<string, string> = {
    critical: '🔴 CRITICAL',
    high: '🟠 HIGH',
    medium: '🟡 MEDIUM',
    low: '🟢 LOW',
    info: 'ℹ️ INFO',
  };
  return badges[severity] || severity;
}

function generateScoreBar(score: number): string {
  const filled = Math.round(score / 10);
  const empty = 10 - filled;
  const bar = '█'.repeat(filled) + '░'.repeat(empty);
  return `\`${bar} ${score}%\``;
}

function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  if (ms < 60000) return `${(ms / 1000).toFixed(1)}s`;
  const m = Math.floor(ms / 60000);
  const s = Math.round((ms % 60000) / 1000);
  return `${m}m ${s}s`;
}